stages:
  - build
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_locally:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/alma9-base
  tags:
    - cvmfs
  script:
    - curl -fsSL https://pixi.sh/install.sh | bash
    - . ~/.bash_profile 
    # - pixi shell -> Is there a way to make this work?
    - pwd
    - ls
    - mkdir build; cd build
    - pixi list
    - pixi run python --version
    - pixi run python ../test.py
    - pixi run which gcc
    - pixi run which cc
    - pixi run which c++
    - pixi run cmake ../source
    - pixi run make
    - source setup.sh
    - pixi run genModels.py

build_image:
  stage: build
  image:
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}"
                       --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
                       --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"