stages:
  - build
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_locally:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/alma9-base
  tags:
    - cvmfs
  script:
    - curl -fsSL https://pixi.sh/install.sh | bash
    - . ~/.bash_profile 
    - pixi shell
    - mkdir build; cd build
    - cmake ../source
    - make
    - source setup.sh

# build_image:
#   stage: build
#   image:
#     name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
#     entrypoint: [""]
#   script:
#     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
#     - /kaniko/executor --context "${CI_PROJECT_DIR}"
#                        --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
#                        --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"