stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.install_pixi:
  before_script:
    # fetch and install pixi locally
    - curl -fsSL https://pixi.sh/install.sh | bash
    - . ~/.bash_profile

build_local:
  extends: .install_pixi
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/alma9-base
  script:
    # run small pixi tests
    - pixi list
    - pixi run python --version
    - pixi run which gcc
    - pixi run which cc
    - pixi run which c++
    # build project
    - pixi run cmake -S source -B build
    - pixi run cmake --build build -j8
  artifacts:
    expire_in: 1 week
    paths:
      - build/

test_genModels:
  extends: .install_pixi
  stage: test
  dependencies:
    - build_local
  script:
    - pixi list
    - ls
    - pwd
    - cd build
    - source setup.sh
    - cd ..
    - mkdir run; cd run
    - pixi run genModels.py

build_docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    # Prepare Kaniko configuration file
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    # Build and push the image
    - |
      # If pipeline runs on the default branch (main): Set tag to "latest"
      if test "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH"; then
        add=""
        tag="latest"
      # If pipeline is a tag pipeline, set tag to the git commit tag
      elif test -n "${CI_COMMIT_TAG}"; then
        add=""
        tag="${CI_COMMIT_TAG}"
      # Else set the tag to the branch name and git commit sha
      else
        add="${CI_COMMIT_REF_SLUG}"
        tag="-${CI_COMMIT_SHORT_SHA}"
      fi
      IMAGE_DESTINATION=${CI_REGISTRY_IMAGE}:${add}${tag}
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${IMAGE_DESTINATION}"
    - echo "Image pushed successfully to ${IMAGE_DESTINATION}"
