[project]
name = "Run3ModelGen"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jonas Wuerzinger <jonas.wuerzinger@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.*"
gfortran = ">=13.2.0,<13.3"
cmake = ">=3.29.2,<3.30"
numpy = ">=1.26.4,<1.27"
pyyaml = ">=6.0.1,<6.1"

[pypi-dependencies]
pyslha = ">=3.2.6"
