[project]
name = "Run3ModelGen"
version = "0.1.1"
description = "Add a short description here"
authors = ["Jonas Wuerzinger <jonas.wuerzinger@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.*"
gfortran = ">=13.2.0,<13.3"
cmake = ">=3.29.2,<3.30"
numpy = ">=1.26.4,<1.27"
pyyaml = ">=6.0.1,<6.1"
cxx-compiler = ">=1.0.0,<1.1"
make = ">=4.3,<5"
which = ">=2.21,<3"

[pypi-dependencies]
pyslha = ">=3.2.6"
uproot = ">=5.3.3"
rich = ">=13.7.1"
structlog = ">=24.1.0"
click = ">=8.1.7"
